version: '2'
services:
  db:
    image: mysql:5.7
    container_name: employee_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=employee_db
      - MYSQL_DATABASE=employee_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8']
    networks:
      main:
        aliases:
          - employee_db
networks:
  main: