version: '2'
services:
  db:
    image: mysql:5.7
    container_name: springBoot
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=springBoot
      - MYSQL_DATABASE=springBoot
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8']
    networks:
      main:
        aliases:
          - springBoot
networks:
  main: